CREATE OR REPLACE PACKAGE CARLOS.PKG_PRODUCTOS AS
    PROCEDURE GET_PRODUCTOS (COD_PRODUCTO IN NUMBER, CUR_PRODUCTOS OUT SYS_REFCURSOR);
END PKG_PRODUCTOS;
/
CREATE OR REPLACE PACKAGE BODY CARLOS.PKG_PRODUCTOS AS
    PROCEDURE GET_PRODUCTOS (COD_PRODUCTO IN NUMBER, CUR_PRODUCTOS OUT SYS_REFCURSOR) IS
    BEGIN
        OPEN CUR_PRODUCTOS FOR
        SELECT  COD, NOMBRE, PU, FECFAB
        FROM    PRODUCTO P
        WHERE   P.COD = COD_PRODUCTO;
    EXCEPTION
     WHEN OTHERS THEN
       DBMS_OUTPUT.PUT_LINE(SQLERRM);
    END GET_PRODUCTOS;
END PKG_PRODUCTOS;
/
